### ISSUE TITLE
Blockstat consumes about 1.9 GB Of memory, then stops processing

### ISSUE THREAD

**Issue by TnTBass** [tdewin/blockstat#2]
Running blockstat against a lot of vbk files (243) in a single directory causes blockstat to consume about 1.9 GB of memory, then stop processing.

Running the command: blockstat -m "c:\path\to\files\*.vbk"

![Annotation 2020-01-28 110921](https://user-images.githubusercontent.com/1081294/73292232-e9c7d280-41be-11ea-9623-57e914a789f4.png)

I can see blockstat start reading the disk, but then the blockstat process drops off to zero disk activity.  The process remains running indefinitely, but never finishes and displays any output.

**Comment by TnTBass** [comment]
Its possible this is due to running against multiple vbk files for VMs stored in a "per VM" basis, rather than vbk files that contain all the VMs.  Eg: I can't run it against the entire folder, I have to pick each VM and run it against all files for that VM.

**Comment by tdewin** [comment]
There is no such limitation because blockstat is not aware of anything Veeam related. It just looks at the blocks and tries to figure out how many of them are "shared". 

However if you use per VM chains, there is little sense in running it against the complete directory of all chains because it will just create a bigger load and there is not data being shared between these chains. 

The tool is quite heavy on memory because it makes brute comparisons. It make a bitmap per fileblock on the filesystem and then runs over each and every file you specify. For each block that is used (64kb) it increase the bitmap. However, this creates a very big bitmap. In theory every block is represented by a 16bit integer so sharing this blocks should not happen that much. So if you have 64KB blocksize, every block is represented by 2B, thus memory usage should be 32768 smaller then the volume you using. E.g if your volume is 64TB, you should see 2GB of mem usage. So in your case, could it be that your volume is around 64TB? (Long time ago, I worked on the project so just doing the theoretical part here)

Anyway, if you could just try to run it chain per chain and let me know how that works, would be useful to get the feedback

**Comment by TnTBass** [comment]
Thanks for the answers @tdewin!  I did run it against each chain and it ran successfully. I came to the same conclusion you had mentioned, eg: there is no point running it against the full directory.  Doing this (however incorrect it may be) does seem to break blockstat though, as it just stops reading the disk.

My volume is 58.2 TB, so that makes sense for the memory usage.
